---
# ansible-playbook /etc/ansible/playbooks/cassandra3x/operate_rolling_restart.yml --extra-vars "target=ansible_inventory_hosts"
- hosts: "{{ target | default('FAIL') }}"
  gather_facts: false
  any_errors_fatal: true
  serial: 1
  roles:
     - cassandra3x_operate_stop
     - cassandra3x_operate_start
